# Generated by Django 5.0.7 on 2024-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_payment_payment_by_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_by_card",
            field=models.CharField(
                choices=[("card", "оплата по карте"), ("cache", "оплата наличными")],
                default="card",
                help_text="введите способ оплаты",
                max_length=5,
                verbose_name="способ оплаты",
            ),
        ),
    ]
