# Generated by Django 5.0.7 on 2024-07-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=255,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте превью курса",
                        null=True,
                        upload_to="materials/course",
                        verbose_name="Превью курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание курса",
                        null=True,
                        verbose_name="Описание курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урока",
                        max_length=255,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте превью урока",
                        null=True,
                        upload_to="materials/lesson",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание урока",
                        null=True,
                        verbose_name="Описание урока",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Введите ссылку на урок",
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на урок",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Введите к какому курсу относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
