# Generated by Django 5.0.7 on 2024-08-03 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_creator_lesson_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_by_card",
                    models.CharField(
                        choices=[
                            ("card", "оплата по карте"),
                            ("cache", "оплата наличными"),
                        ],
                        default="card",
                        help_text="введите способ оплаты",
                        max_length=5,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату оплаты",
                        verbose_name="дата оплаты",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True,
                        help_text="введите сумму оплаты",
                        null=True,
                        verbose_name="сумма оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="введите оплаченный курс",
                        null=True,
                        on_delete=models.SET("Данного курса больше не существует"),
                        to="materials.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="введите оплаченный курс",
                        null=True,
                        on_delete=models.SET("Данного урока больше не существует"),
                        to="materials.lesson",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
