# Generated by Django 5.0.7 on 2024-08-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                help_text="введите курс",
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="курс",
            ),
        ),
    ]
