# Generated by Django 5.0.7 on 2024-08-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
    ]
