# Generated by Django 5.0.7 on 2024-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_course_creator_alter_lesson_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="введите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="введите идентификатор сессии",
                max_length=255,
                null=True,
                verbose_name="идентификатор сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                default=0, help_text="введите сумму оплаты", verbose_name="сумма оплаты"
            ),
        ),
    ]
