# Generated by Django 5.0.7 on 2024-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_payment_link_payment_session_id_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True,
                help_text="введите идентификатор продукта",
                max_length=255,
                null=True,
                verbose_name="идентификатор продукта",
            ),
        ),
    ]
