# Generated by Django 5.0.7 on 2024-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True,
                help_text="введите дату последнего обновления",
                null=True,
                verbose_name="Последнее обновление",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="введите статус подписки",
                null=True,
                verbose_name="cтатус подписки",
            ),
        ),
    ]
