# Generated by Django 5.0.7 on 2024-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_course_last_update_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True,
                help_text="введите дату последнего обновления",
                null=True,
                verbose_name="Последнее обновление",
            ),
        ),
    ]
